---
deployment:
  tasks:
    - export DEPLOYPATH=/home/tkmatosi/public_html/
    - /bin/rsync -azh --delete \
        --exclude=".git" --exclude=".github" --exclude="node_modules" \
        ./ $DEPLOYPATH
