---
deployment:
  tasks:
    - export DEPLOY_SRC="$PWD"
    - export DEPLOY_DST="$HOME/public_html"   # ajuste se seu site estiver em outra pasta
    - /bin/rsync -av --delete \
        --exclude ".git" \
        --exclude ".github" \
        --exclude "README.md" \
        "$DEPLOY_SRC"/ "$DEPLOY_DST"/
